### ISSUE TITLE
format_note error

### ISSUE THREAD

**Issue by eljaouharielmehdi** [ibaiGorordo/cap_from_youtube#1]
Hi i'm trying this for the first time and it seems like it's note working, could some one explain to me why this error occur.
[youtube] Extracting URL: https://youtu.be/Yv4vPDqoOmQ
[youtube] Yv4vPDqoOmQ: Downloading webpage
[youtube] Yv4vPDqoOmQ: Downloading ios player API JSON
[youtube] Yv4vPDqoOmQ: Downloading android player API JSON
[youtube] Yv4vPDqoOmQ: Downloading m3u8 information
Traceback (most recent call last):
  File "C:/Users/DELL/Desktop/pafy test.py", line 6, in <module>
    cap = cap_from_youtube(youtube_url)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\cap_from_youtube\cap_from_youtube.py", line 46, in cap_from_youtube
    streams, resolutions = list_video_streams(url)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\cap_from_youtube\cap_from_youtube.py", line 33, in list_video_streams
    streams = [VideoStream(format)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\cap_from_youtube\cap_from_youtube.py", line 33, in <listcomp>
    streams = [VideoStream(format)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\cap_from_youtube\cap_from_youtube.py", line 17, in __init__
    self.resolution = video_format['format_note']
KeyError: 'format_note'

this is the basic code i did:
import cv2
from cap_from_youtube import cap_from_youtube, list_video_streams

youtube_url = 'https://youtu.be/Yv4vPDqoOmQ'
cap = cap_from_youtube(youtube_url)

#streams, resolutions = list_video_streams(youtube_url)

#for stream in streams:
#    print(stream)

"""   
cv2.namedWindow('video', cv2.WINDOW_NORMAL)
while True:
    ret, frame = cap.read()
    if not ret:
        break
    cv2.imshow('video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
"""

**Comment by rsardal** [comment]
I'm having this issue too, were you able to figure out a solution?

**Comment by ibaiGorordo** [comment]
I just added a quick fix, it should be fine now. I will try to update the PyPI package later.

**Comment by ibaiGorordo** [comment]
Closing, I just released the new version
